version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 
  spacelight-data:
    build: 
      context: ../
      dockerfile: build/Dockerfile
    image: "beancodede/spacelight-data:latest"
    container_name: spacelight-data
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
    ports:
      - 1203:1203
    volumes: 
      - ./token:/token
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres